# Site settings
title: Sicarim's Lab
description: Technology, Game, Development All things 
cover: /tree/master/assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/sicarim/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://sicarim.github.io" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
#facebook: facebook
#twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-remote-theme


# Settings for rake task
safe: False
lsi: False
username: DoYun #github username
repo: sicarim #github repository
branch: master #branch
relative_source: ../sicarim/ #source directory
destination: ../sicarim-pages/ #destination directory
production_url:  https://sicarim.github.io/
source_url:  https://github.com/Sicarim/sicarim.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
